### ISSUE TITLE
IE11: Description field

### ISSUE THREAD

**Issue by Uafinder** [anhnt/ksurvey#1]
![image](https://cloud.githubusercontent.com/assets/1945230/13058011/bdbde2ae-d428-11e5-846a-8532e921cf37.png)
![image](https://cloud.githubusercontent.com/assets/1945230/13058016/c6044fa2-d428-11e5-8658-9c2a00b39625.png)
Description field in IE could be a bit larger like in FF

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
yup
