### ISSUE TITLE
When survey has no dates it doesn't gain "done" status when done

### ISSUE THREAD

**Issue by Uafinder** [anhnt/ksurvey#14]
![image](https://cloud.githubusercontent.com/assets/1945230/13088657/d00bd2ae-d4f5-11e5-9d23-cc970ac4f769.png)
![image](https://cloud.githubusercontent.com/assets/1945230/13088662/da222586-d4f5-11e5-9884-8fde438dba28.png)

When you have created survey without start/end dates, and finish it, it wouldn't gain "done" status. And "start" button will no be disabled as it should be.

**Comment by anhnt** [comment]
fixed :)

**Comment by Uafinder** [comment]
Yup
