### ISSUE TITLE
the survey should have a page where users can see full poll content and results, and comment

### ISSUE THREAD

**Issue by anhnt** [anhnt/ksurvey#16]

**Comment by anhnt** [comment]
Result page for user who finished the survey can be like this http://anh.olhub.com/ksurvey/survey-INGwyeSOFniw4aBMwD4niw4STEr5Uu/result

**Comment by Uafinder** [comment]
Yeah, but there is no possibility to leave a comment there

**Comment by anhnt** [comment]
comments should work at the bottom of page

**Comment by Uafinder** [comment]
![image](https://cloud.githubusercontent.com/assets/1945230/13330645/6c056806-dc02-11e5-90c0-d36b71a8d9e6.png)
Yeah, but there is no possibility to leave a comment

**Comment by anhnt** [comment]
just logged in as vladqa099@mailinator.com and it works for me http://vladqa099.olhub.com/ksurvey/survey-Hoz3Yxg04VRgYgEBB3qSJuD5CUNlfD/result

**Comment by Uafinder** [comment]
it works... weird... definitely there wasn't such possibility
