### ISSUE TITLE
Group add and remove cause a bug with group name

### ISSUE THREAD

**Issue by Uafinder** [anhnt/ksurvey#19]
![image](https://cloud.githubusercontent.com/assets/1945230/13330881/95869ba4-dc03-11e5-9215-b2fcf7daffe7.png)

**Comment by anhnt** [comment]
can you show me how to reproduce that bug please?

**Comment by Uafinder** [comment]
Yo can add any group to access Ksurvey, and then remove it
![image](https://cloud.githubusercontent.com/assets/1945230/13473464/23843250-e0c2-11e5-8f76-68f377a96276.png)
![image](https://cloud.githubusercontent.com/assets/1945230/13473475/3328e9c6-e0c2-11e5-8b1a-a64179402a02.png)

**Comment by anhnt** [comment]
fixed

**Comment by Uafinder** [comment]
Yup. looks ok
