### ISSUE TITLE
Adding new answers to the multichoice question

### ISSUE THREAD

**Issue by Uafinder** [anhnt/ksurvey#3]
![image](https://cloud.githubusercontent.com/assets/1945230/13058071/32798ce2-d429-11e5-85cc-88f98cfef177.png)
It's not quite understand what should be done to save answer.
It is saving now by pressing enter on the keyboard. Possible would be great to save it by pressing some additional button (+) or loosing focus from the field.

**Comment by anhnt** [comment]
this works like FB comments does at the moment. pending for now

**Comment by anhnt** [comment]
i think we can close this
