### ISSUE TITLE
things which are not ready 

### ISSUE THREAD

**Issue by Uafinder** [anhnt/ksurvey#9]
- the survey should be able to generate a bar graph showing answers which is shown on the dashboard for users who have submitted previously
  It's empty now, either on dashboard or on survey page
  ![image](https://cloud.githubusercontent.com/assets/1945230/13058849/a1cebca2-d42e-11e5-9cdb-084dd37317a2.png)
- the survey should have a page where users can see full poll content and results, and comment
  Haven't see it at all
- start and end dates (optional)
  It's mandatory at the moment
  ![image](https://cloud.githubusercontent.com/assets/1945230/13058871/c986d234-d42e-11e5-9ae6-2015db7563d8.png)

**Comment by anhnt** [comment]
start and end dates (optional) -- done

**Comment by anhnt** [comment]
@Uafinder do you think user should see all plain text answers?

**Comment by Uafinder** [comment]
No, i don't think so...

**Comment by anhnt** [comment]
closing this issue, move to https://github.com/anhnt/ksurvey/issues/16
